js/adapt-hotgrid.js
Amended alignItem function so that it now calculates as a % rather than using px so if you switch between orientations on a tablet, the hotgrid items remain centrally aligned.
=> Converted alignItem function from px to %

js/adapt-hotgrid.js
On iPad: 
With Trickle set on an article containing Hot Grid, scrolling too quickly down the page would prevent all Hot Grid images from loading. Seems Trickle was calculating page height before the Hot Grid component could expand to encompass the loading images. The result was the Hot Grid was being cut-off by Trickle. This could be alleviated by scrolling back up the page and allowing the Hot Grid to reload.
This inconvenience was eliminated by using imageready with "_setReadyStatus()".
=> Wrap setReadyStatus with imageready

README.md, bower.json, js/adapt-hotgrid.js, less/hotgrid.less, templates/hotgrid.hbs
Reduced JS code to setup item widths based upon '_columns' value.
Amended LESS to use 'display: inline-block' style instead.
Updated template file to use `<button>` tag instead of `<a>` tag for OS Voiceover compatibility.
Bumped bower.json and readMe version to 3 as this change has the potential to introduce breaking changes.
=> Refactored column setup, changed <a> to <button>

less/hotgridPopup.less
Resolves https://github.com/cgkineo/adapt-hotgrid/issues/74
* Set line height of the hotgrid popup count area to 1
=> Set popup count line height

js/hotgridPopupView.js
Resolves https://github.com/cgkineo/adapt-hotgrid/issues/76
=> Prevent toggleHidden from targeting child elements causing images without 'alt' to be read by screen reader

js/hotgridPopupView.js, js/hotgridView.js, less/hotgridPopup.less
Fixes #86
* Removes 'visibility: hidden' from Hotgrid popup disabled paging buttons
1. Add a Hotgrid component to a course.
1. Click on an item to open the Notify popup.
1. The disabled buttons should be visible.
Requires https://github.com/adaptlearning/adapt-contrib-core/pull/221
=> Update: Remove visibility: hidden from disabled popup paging buttons (fixes #86)

less/hotgrid.less, templates/hotgrid.hbs, templates/hotgridPopup.hbs
Resolves https://github.com/cgkineo/adapt-hotgrid/issues/84
* Converted button divs to spans
* Visual fix for divs to spans conversion
=> Converted button divs to spans

templates/hotgridPopupToolbar.jsx
Fixes #102 
* Changes the Hotgrid Notify close button's aria-label to the correct identifier
=> Fix: Fix popup close button aria-label (fixes #102)

templates/hotgridPopupToolbar.jsx
Fixes #111 
* hotgrid popup toolbar count aria-hidden=true (#111)
[//]: # (List appropriate steps for testing if needed)
1. Open a hotgrid item using a screen reader navigate through popup toolbar 
2. Ensure the popup count is not read out
=> Fix: hotgrid popup toolbar count aria-hidden=true

templates/hotgridPopup.jsx
Fixes (#109) 
* Fix: Move popup navigation below content for screen readers (#109)
[//]: # (List appropriate steps for testing if needed)
1. Navigate to hotgrid using screen reader
2. Open an item to check it focuses on content rather than popup toolbar
[//]: # (Mention any other dependencies)
=> Fix: Move popup toolbar below content for screen readers (fixes #109)

templates/hotgrid.jsx
Fixes (#107)
* aria-haspopup removed from hotgrid buttons (#107)
[//]: # (List appropriate steps for testing if needed)
1. Using Jaws, navigate to Hotgrid
2. Move between items using keyboard arrows
3. Open an item and close
4. Use arrows to move to a different item to check it's not just scrolling the page
aria-haspopup has some issues with various screen readers and is not fully compatible (https://www.digitala11y.com/aria-haspopup-properties/). …
=> Fix: aria-haspopup removed from hotgrid buttons (Fixes (#107))

js/HotgridView.js, package.json
fixes https://github.com/cgkineo/adapt-hotgrid/issues/122 
requires https://github.com/adaptlearning/adapt-contrib-core/pull/372
- Moved breakpoint to medium from large
- FW version bumped inline with core code
=> Fix: Realign breakpoint for column layout to medium and above (fixes #122)

templates/hotgridPopupToolbar.jsx
Fixes #113 
* Jaws highlight issue for close button (fixes #113)
[//]: # (List appropriate steps for testing if needed)
1. Using Jaws (2023), open a hotgrid item and navigate to the close button
2. Check the highlight box of the button 
[//]: # (Mention any other dependencies)
=> Fix: Jaws highlight issue for close button (fixes #113)

templates/hotgridPopup.jsx
The popup title, `.hotgrid-popup__item-title` is read by a screen reader but it isn't announced as a 'heading' neither is the heading aria-level announced. 
The current implementation doesn't have a `role='heading'` assigned which is required for `aria-level `to read.
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/120
=> Fix: Item popup title missing ARIA heading role (fixes #120)

templates/hotgridPopup.jsx
To support [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper.
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/124
=> Fix: compile reactHelpers (fixes #124)

example.json
The example title for the Hotgrid item and the item popup are the wrong way round. The item should be 'Grid item..' and the popup should be 'Item title..'
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/130
=> Fix: Update example.json (fixes #130) 

templates/hotgrid.jsx, templates/hotgridPopup.jsx
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/124
To support [a11y_alt_text](https://github.com/adaptlearning/adapt-contrib-core/commit/a92c7ffdb431bdf126e080c009b3b9c324642755) helper tag.
Add `a11y_alt_text` helper to Hotgrid item `title` and item `_graphic` `title`.
e.g. `{{a11y_alt_text '$5bn' 'five billion dollars'}}`.
In your course, go to the Hotgrid item and trigger popup. The `a11y_alt_text` helper syntax shouldn't be visible within the popup display text and instead should just display '$5bn'.
Using the browser devtools, inspect '$5bn' and the helper should have split out the on screen text and a11y text e.g.
`<span aria-hidden="true">$5bn</span><span class="aria-label">five billion dollars</span>`
=> Fix: compile title (fixes #124)

less/hotgridPopup.less, templates/hotgridPopupToolbar.jsx
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/126
- Apply `.notify__btn-icon` to popup icon buttons to inherit styles from [Vanilla notify.less](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/142b4fde60d638e280d04d691c63fbe62bd5abfe/less/core/notify.less#LL74C3-L86C4).
- Remove the duplicate styles from Hotgrid (these just repeat what's now inherited from Vanilla). 
This means the default Notify button icon style is set in one place but we still have plugin specific classes to target should you want to style these different - although there's good reason for keeping UI button styling consistent.
Ref: similar PR raised for Hotgraphic https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/276
=> Update: add generic .notify__btn-icon class (fixes #126)

README.md, js/HotgridView.js, templates/hotgrid.jsx
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/118
_Note, breakpoints were introduced after the issue was raised, so screen sizes mentioned in the issue have since changed._
The default `width: 50%` defined in the [CSS](https://github.com/cgkineo/adapt-hotgrid/blob/728b2a24ac85f082c56f524ffa03de3c166bee06/less/hotgrid.less#L10) was getting overwritten via the [JS inline style](https://github.com/cgkineo/adapt-hotgrid/blob/728b2a24ac85f082c56f524ffa03de3c166bee06/js/HotgridView.js#L43) regardless of screen size.
The inline style should only apply when screen size is `medium` and above, and inherit from the CSS otherwise. I've updated this for consistency with GMCQ which also uses [_columns](https://github.com/adaptlearning/adapt-contrib-gmcq/blob/53c5724364f3c416c0eae24ac8992104e05ea …
=> Fix: Responsive item width inconsistency (fixes #118)

js/HotgridView.js
#137 
* Remove this.render on device change (fixes #137)
=> Fix: Remove this.render on device change (fixes #137)

README.md, less/hotgridPopup.less, package.json, properties.schema, schema/component.schema.json, templates/hotgridPopup.jsx
- Expand popup image `_imageAlignment` to support `top` and `bottom` layout as per Core Notify.
- Make the popup item DOM order match the visual order to meet WCAG success criteria - https://www.w3.org/TR/WCAG20-TECHS/C27.html
- Use Core image partial to reduce code duplication.
**Testing PR**
This requires testing with [Core PR pull/479](https://github.com/adaptlearning/adapt-contrib-core/pull/479) for `classNamePrefixSeparator` support.
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/139
=> Update: expand _imageAlignment properties and set popup item DOM order (fixes #139)

README.md, example.json, templates/hotgrid.jsx
Fix #143 
* Adds the `_items._classes` to `.hotgrid__item` to assist with styling.
* Retains the custom class on the Hotgrid popups.
=> Fix: Add _classes to hotgrid__item (fixes #143)

properties.schema
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/146
* Set `title` as `required`. Without a title, the popup `dialog` won't be properly identified by assistive technologies.
=> Fix: Title is required to set notify popup dialog label (fixes #146)

properties.schema, schema/component.schema.json
This should have been implemented as part of [merged PR - Title is required to set notify popup dialog label](https://github.com/cgkineo/adapt-hotgrid/pull/147) for consistency with [Hotgraphic PR](https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/295). Branch re-opened.
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/146
=> Update: set item Title as required in component schema (fixes #146)

templates/hotgridPopup.jsx
Fixes https://github.com/cgkineo/adapt-hotgrid/issues/152
* Changed 'notify-heading' to id from class such that the `aria-labelledby` on the dialog can find the element
=> Fix: notify aria-labelledby element id (fixes #152)

templates/hotgridPopup.jsx
Fixes #154.
* React HotgridPopup error for conditional `id` attribute.
=> Fix: React HotgridPopup error for conditional `id` attribute

properties.schema, schema/component.schema.json
Fix #156 
* Update "Item Popup Classes" schema description to remove reference to `align-image-left` class
=> Fix: Update "Item Popup Classes" schema description to remove align class (fix #156)

js/HotgridView.js, less/hotgrid.less, templates/hotgrid.jsx
Fixes: #158
* Converted inline item width to CSS variable
=> Fix: Converted inline item width to CSS variable (fixes #158)
