cgkineo/adapt-hotgrid

README.md
bower.json
example.json
js/adapt-hotgrid.js
less/hotgrid.less
templates/hotgrid.hbs

- RTL styling updated.
- template ARIA updated.
- redundant config removed from example.json.
- readMe.md and bower.json updated.

v2 ready updates

---

bower.json
properties.schema

Added supported layout to ensure it works in latest version of AT

Fix to work in latest version of AT

---

less/hotgrid.less

remove alpha from tap highlight color

---

README.md
bower.json
example.json
js/adapt-hotgrid.js
js/hotgridModel.js
js/hotgridPopupView.js
js/hotgridView.js
less/hotgrid.less
properties.schema
templates/hotgrid.hbs
templates/hotgridPopup.hbs

updates to bring in line with hotgraphic rework

---

js/adapt-hotgrid.js
less/hotgrid.less
properties.schema
templates/hotgrid.hbs

Refactors the notify event to off load the rendering to the template
Tweaks to the CSS states (if < 1 image)
Add _hasRoundedCorners flag to be set in component json

Hotgrid updates 2017-11-17

---

README.md
bower.json
properties.schema
templates/hotgridPopup.hbs

fix for issue #43

---

less/hotgrid.less
templates/hotgrid.hbs

amends to get hotgrid image states working again

---

README.md
bower.json
example.json
js/hotgridView.js
properties.schema

via new `_setCompletionOn`, inline with Hot Graphic and other (interactive) adapt core presentation components.
Bumped FW dependency to >=3.3 as this needs the 'complete on inview' functionality in `ComponentView` that was added in v3.3.0

added support for inview completion

---

less/hotgridPopup.less
templates/hotgridPopup.hbs

Resolves https://github.com/cgkineo/adapt-hotgrid/issues/58

Toolbar no pagination fix

---

README.md
bower.json
js/hotgridPopupView.js
templates/hotgridPopup.hbs

alt text shouldn't be required

---

README.md
example.json
less/hotgridPopup.less
properties.schema

Resolves https://github.com/cgkineo/adapt-hotgrid/issues/65
* Added media query to '.hide-desktop-image' class 
* Added new class that hides item pop up image for all screen resolutions

Class fix, added hide-popup-image class

---

less/hotgrid.less
less/hotgridPopup.less

Resolves https://github.com/cgkineo/adapt-hotgrid/issues/68

Less tidy up

---

less/hotgridPopup.less

Resolves https://github.com/cgkineo/adapt-hotgrid/issues/70
* Increased text area width by 10% and reduced image area width by 10%

Adjusted body / image widths

---

less/hotgridPopup.less

Resolves https://github.com/cgkineo/adapt-hotgrid/issues/72
* Increases item padding to mirror other elements in Adapt

Increased item spacing

---

README.md
example.json
properties.schema

+ added alt text guidance
https://github.com/adaptlearning/adapt_framework/issues/2939

remove placeholder alt text from example

---

less/hotgrid.less
less/hotgridPopup.less

Related to https://github.com/adaptlearning/adapt_framework/issues/2685

btn-icon variable support

---

README.md
example.json
properties.schema
templates/hotgridPopup.hbs

Fixes: #90 
* Consolidates the image alignment of a hotgrid item pop up into a json property that applies alignment classes on the parent depending on property value

Update: image alignment property (fixes: #90)

---

properties.schema

#100
* Add missing inputType values to the _globals properties

Fix: Add missing inputType schema values (fixes #100)

---

README.md

Fixes #105
* README.md - Remove plugin version number
* README.md - Minor grammatical fix

Fix: README.md - Remove version number, minor grammatical fix (fixes #105)

---

less/hotgrid.less
templates/hotgrid.jsx

Fixes #99 
* Adds a completion icon to the visited item state

Fix: Add completion icon styles (fixes #99)

---

example.json
properties.schema
schema/component.schema.json

#95 
* default instruction text added to schema (fixes #95)

Fix: default instruction text added to schema (fixes #95)

---

README.md

For #133 
* Removes outdated supported framework version from readme to prevent confusion

Update: Framework versions removed from readme

---

README.md
example.json
properties.schema
schema/component.schema.json
templates/hotgrid.jsx

Fix #119 
* Adds a new option `_alwaysShowIcon` to show the plus icon
* Update schemas and docs
* Add missing `_isRound` option to readme.

Fix: Add option to always show the plus icon (fixes #119)

---

js/HotgridView.js

#160 
* Check if popup close event is relevant

Fix: check if popup close event is relevant (fixes #160)

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/issue_template.md

Fixes #162 
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template

Chore: Add support for new issue experience (fixes #162)
